Repository googleapis/github-repo-automation, pull requests merged in 2019-05, with the labels that each got.

#267 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#268 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#270 fix!: stop supporting Node.js v6
  package.json
Labels: cla: yes

#271 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#272 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#274 build: windows and code coverage config updates
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
  .kokoro/test.bat
  synth.metadata
Labels: cla: yes

#277 build: configure automated releases
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node10/test.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#279 refactor: drop usage of pify
  package.json
  src/lib/config.ts
  src/lib/update-repo.ts
  src/sync.ts
Labels: cla: yes

#283 chore: add kokoro job for publishing docs
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  synth.metadata
Labels: cla: yes

#285 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#286 chore: release 2.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#289 fix: make other PR commands concurrent
  package.json
  src/lib/prIterator.ts
  src/merge-prs.ts
  src/reject-prs.ts
  src/tag-prs.ts
  src/update-prs.ts
Labels: cla: yes

#288 build: don't run build scripts in verbose mode
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
