Repository googleapis/github-repo-automation, pull requests merged in 2020-07, with the labels that each got.

#424 docs: consistently use name `config.yaml`
  README.md
Labels: cla: yes

#425 fix: allow regex search for branch listing
  src/lib/asyncItemIterator.ts
  src/list-prs.ts
Labels: cla: yes

#427 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#428 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#432 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#431 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#436 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#435 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#437 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#438 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#439 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#440 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
