Repository googleapis/github-repo-automation, pull requests merged in 2021-02, with the labels that each got.

#484 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: automerge, cla: yes

#485 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#486 fix(deps): upgrade to js-yaml 4.0
  package.json
  src/lib/config.ts
Labels: cla: yes
